server:
  port: 9020
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: tourist-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
              - POST
              - GET
              - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true        
    
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/api/v1/tourist/register
            
        - id: display-service
          uri: lb://display-service
          predicates:
            - Path=/api/v1/tourist/getAll        
      